# CBS - Clyso Build System
# Copyright (C) 2025  Clyso GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

FROM python:3.13-alpine3.20 AS base

# hadolint ignore=DL3018
RUN apk --no-cache add podman=5.2.5-r0 curl

# hadolint ignore=DL4006
RUN curl -LsSf https://astral.sh/uv/install.sh | \
  UV_INSTALL_DIR=/usr/bin \
  UV_DISABLE_UPDATE=1 \
  UV_NO_MODIFY_PATH=1 \
  /bin/sh

WORKDIR /cbs/server

VOLUME [ "/cbs/config" ]

FROM base AS cbsd-dev-server

ENTRYPOINT [ \
  "/cbs/server/cbsd/entrypoint-dev.sh", \
  "server" \
  ]


FROM base AS cbsd-dev-worker

VOLUME [ "/cbs/scratch" ]
VOLUME [ "/var/lib/containers" ]
VOLUME [ "/cbs/components" ]
VOLUME [ "/cbs/containers" ]
VOLUME [ "/cbs/ccache" ]
VOLUME [ "/cbs/server" ]

ENTRYPOINT [ \
  "/cbs/server/cbsd/entrypoint-dev.sh", \
  "worker" \
  ]
