FROM docker.io/caddy:2.11

RUN apk add --no-cache openssl=3.5.5-r0

RUN mkdir -p /etc/caddy/certs

# hadolint ignore=DL3059
RUN openssl req \
  -x509 \
  -newkey rsa:4096 \
  -keyout /etc/caddy/certs/cert.key \
  -out /etc/caddy/certs/cert.pem \
  -days 3650 \
  -nodes \
  -subj "/CN=cbs"
